---
- name: Create GPO to map Snare-Products Drive
  hosts: DC
  gather_facts: no
  vars:
    gpo_name: MapSnareProductsDrive
    gpo_description: "GPO to map Snare-Products shared drive"
    share_path: "\\\\{{ domain_name }}\\Snare-Products"
    domain_dn: "DC={{ domain_short|lower }},DC=lab,DC=local"
    ps_script_src: "~/ad-training-lab/ansible/playbooks/Snare-Products/create_gpo_map_drive.ps1"

  tasks:
    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy PowerShell script to Windows machine
      win_copy:
        src: "{{ ps_script_src }}"
        dest: C:\Temp\create_gpo_map_drive.ps1

    - name: Execute PowerShell script to create and configure GPO
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Temp\create_gpo_map_drive.ps1 -GpoName "{{ gpo_name }}" -GpoDescription "{{ gpo_description }}" -SharePath "{{ share_path }}" -DomainDn "{{ domain_dn }}"

    - name: Clean up PowerShell script
      win_file:
        path: C:\Temp\create_gpo_map_drive.ps1
        state: absent
