ansible_connection: ssh
dns_forwarders: 1.1.1.1

domain_short: SnareTraining
domain_name: '{{ domain_short|lower }}lab.local'

domain_admin_login: '{{ domain_short }}\Administrator'
domain_admin_ssh: '{{ domain_short }}\\Administrator'
domain_admin_password: DomainAdminPassword.
safe_mode_pass: SafeModePassword.

ca_name: '{{ domain_short }}-CA'


first_user: 'snare'

first_user_login: '{{ domain_short }}\{{ first_user }}'
first_user_ssh: '{{ domain_short }}\{{ first_user }}'
first_user_password: 'Password1!'
