ansible_connection: ssh
dns_forwarders: 1.1.1.1

domain_short: SnareTraining
domain_name: '{{ domain_short|lower }}lab.local'

domain_admin_login: '{{ domain_short }}\Administrator'
domain_admin_ssh: '{{ domain_short }}\\Administrator'
domain_admin_password: P@ssw0rd
safe_mode_pass: SafeModePassword.

ca_name: '{{ domain_short }}-CA'

# used for vulns
server_admin: 'fsadmin'
web_admin: 'webadmin'
first_user: 'wsadmin'

first_user_login: '{{ domain_short }}\{{ first_user }}'
first_user_ssh: '{{ domain_short }}\{{ first_user }}'
first_user_password: 'snaretest'

server_admin_login: '{{ domain_short }}\{{ server_admin }}'
server_admin_ssh: '{{ domain_short }}\\{{ server_admin }}'
server_admin_password: 'snaretest'

web_admin_login: '{{ domain_short}}\webadmin'
web_admin_ssh: '{{ domain_short}}\\webadmin'
web_admin_password: 'snaretest'
