---
- name: CONFIGURING CERTIFICATE SERVICES
  hosts: MSSQL-Agent
  gather_facts: no
  tasks:
    - name: Debug ADCS prerequisite installation
      debug:
        msg: "Installing ADCS prerequisites"

    - name: Install ADCS
      win_feature:
        name:
        - AD-Certificate
        - ADCS-Cert-Authority
        - ADCS-Online-Cert
        - ADCS-Web-Enrollment
        - RSAT-Role-Tools
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature

    - name: Debug ADCS prerequisite installation result
      debug:
        msg: "ADCS prerequisite installation result: {{ win_feature }}"

    - name: Install-ADCSCertificationAuthority-PS
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param (
              [String]
              $da_login,

              [String]
              $da_pass
          )
          $pass = ConvertTo-SecureString $da_pass -AsPlainText -Force
          $Cred = New-Object System.Management.Automation.PSCredential ($da_login, $pass)
          try {
            Install-AdcsCertificationAuthority -Credential $Cred -CAType EnterpriseRootCA -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -KeyLength 2048 -HashAlgorithmName SHA256 -ValidityPeriod Years -ValidityPeriodUnits 5 -CACommonName "{{ ca_name }}" -Force
            $Ansible.Changed = $true
          } catch {
            $Ansible.Changed = $false
          }
        error_action: stop
        parameters:
          da_login: "{{ domain_admin_login }}"
          da_pass: "{{ domain_admin_password }}"

    - name: Enable Web Enrollment
      ansible.windows.win_powershell:
        script: |
          [CmdletBinding()]
          param ()
          try {
            Install-AdcsWebEnrollment -Force
            $Ansible.Changed = $true
          } catch {
            $Ansible.Changed = $false
          }

    - name: Refresh group policy
      win_command: gpupdate /force

    - name: Debug final reboot initiation
      debug:
        msg: "Rebooting the server to apply all configurations"

    - name: Force reboot the server after all tasks are done
      win_reboot:
      register: final_reboot_status

    - name: Wait for server to come back online after final reboot
      wait_for_connection:
        timeout: 600
      when: final_reboot_status.changed
