---
- name: CONFIGURING FILESERVER
  hosts: FS
  gather_facts: no
  tasks:
    - name: Installing FS-FileServer feature
      win_feature:
        name:
          - FS-FileServer
        include_sub_features: yes
        state: present

    - name: Creating SharedFolder directory
      win_file:
        path: C:\SharedFolder
        state: directory

    - name: Creating FileServer shared folder
      win_share:
        name: SharedFolder
        description: All-in shared folder
        path: C:\SharedFolder
        list: yes
        full: '{{ domain_short }}\Domain Admins'
        change: '{{ domain_short }}\Domain Users'
        read: Everyone
    
    - name: Add Snare Account to localadmin group
      win_group_membership:
        name: Administrators
        members:
          - '{{ first_user_login }}'
        state: present
