---
- name: Configure Server and Install Microsoft SQL Server
  hosts: MSSQL
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename

    - name: Debug rename output
      debug:
        msg: "Server rename result: {{ rename }}"

    - name: Reboot after rename if required
      win_reboot:
      when: rename.reboot_required
      register: rename_reboot_status

    - name: Wait for server to come back online after rename reboot
      wait_for_connection:
        timeout: 600
      when: rename_reboot_status.changed

    - name: Debug DNS server
      debug:
        msg: "DNS server will be set to {{ hostvars['DC']['ansible_host'] }}"

    - name: Set DNS to Domain Controller
      win_dns_client:
        adapter_names: '*'
        dns_servers:
        - "{{ hostvars['DC']['ansible_host'] }}"

    - name: Debug domain join parameters
      debug:
        msg: "Joining domain {{ domain_name }} with user Administrator@{{ domain_name }}"

    - name: Join Domain
      microsoft.ad.membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "Administrator@{{ domain_name }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: true
      register: join_domain_status

    - name: Reboot after domain join if required
      win_reboot:
      when: join_domain_status.changed
      register: domain_reboot_status

    - name: Wait for server to come back online after domain join reboot
      wait_for_connection:
        timeout: 600
      when: domain_reboot_status.changed

    - name: Debug mapped drive parameters
      debug:
        msg: "Mapping shared folder to Z: drive with path \\\\fs.{{ domain_name }}\\SharedFolder"

    - name: Map shared folder
      community.windows.win_mapped_drive:
        letter: 'Z'
        path: \\fs.{{ domain_name }}\SharedFolder
        state: present

    - name: Debug autologon parameters
      debug:
        msg: "Setting autologon for user {{ snare_admin_login }}"

    - name: Set autologon for specific user
      community.windows.win_auto_logon:
        username: '{{ snare_admin_login }}'
        password: '{{ snare_admin_password }}'

    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Debug MSSQL installer download
      debug:
        msg: "Downloading MSSQL installer"

    - name: Download MSSQL installer
      win_get_url:
        url: https://go.microsoft.com/fwlink/?linkid=866662  # Replace with the correct URL for the desired SQL Server version
        dest: C:\Temp\SQLServer2019.exe

    - name: Debug MSSQL installation initiation
      debug:
        msg: "Installing MSSQL Server"

    - name: Install MSSQL Server
      win_shell: |
        Start-Process -FilePath C:\Temp\SQLServer2019.exe -ArgumentList '/qs', '/ACTION=Install', '/FEATURES=SQLENGINE', '/INSTANCENAME=MSSQLSERVER', '/SECURITYMODE=SQL', '/SAPWD=YourStrong!Passw0rd', '/IACCEPTSQLSERVERLICENSETERMS' -NoNewWindow -Wait
      args:
        executable: powershell.exe

    - name: Ensure MSSQL service is running
      win_service:
        name: MSSQLSERVER
        start_mode: auto
        state: started

    - name: Debug SQL script creation
      debug:
        msg: "Creating SQL script to grant sysadmin permissions"

    - name: Create SQL script to grant sysadmin permissions
      win_copy:
        content: |
          USE [master];
          GO
          ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\SYSTEM];
          GO
        dest: C:\Temp\grant_sysadmin.sql

    - name: Debug SQL script execution
      debug:
        msg: "Executing SQL script to grant sysadmin permissions"

    - name: Execute SQL script to grant sysadmin permissions
      win_shell: |
        sqlcmd -S .\MSSQLSERVER -i C:\Temp\grant_sysadmin.sql
      args:
        executable: cmd.exe

    - name: Clean up installation files and scripts
      win_file:
        path: C:\Temp\SQLServer2019.exe
        state: absent

    - name: Clean up SQL script
      win_file:
        path: C:\Temp\grant_sysadmin.sql
        state: absent

    - name: Debug final reboot initiation
      debug:
        msg: "Rebooting the server to apply all configurations"

    - name: Force reboot the server after all tasks are done
      win_reboot:
      register: final_reboot_status

    - name: Wait for server to come back online after final reboot
      wait_for_connection:
        timeout: 600
      when: final_reboot_status.changed
