---
- name: Configure Server and Install Microsoft SQL Server
  hosts: MSSQL
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename
      
    - name: Reboot after rename
      win_reboot:
      when: rename.reboot_required
      
    - name: Set DNS to Domain Controller
      win_dns_client:
        adapter_names: '*'
        dns_servers:
        - "{{ hostvars['DC']['ansible_host'] }}"
      
    - name: Join Domain
      microsoft.ad.membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: Administrator@{{ domain_name }}
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: true

    - name: Map shared folder
      community.windows.win_mapped_drive:
        letter: 'Z'
        path: \\fs.{{ domain_name }}\SharedFolder
        state: present

    - name: Set autologon for specific user
      community.windows.win_auto_logon:
        username: '{{ snare_admin_login }}'
        password: '{{ snare_admin_login }}'

    - name: Ensure C:\Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Download MSSQL installer
      win_get_url:
        url: https://go.microsoft.com/fwlink/?linkid=866662  # Replace with the correct URL for the desired SQL Server version
        dest: C:\Temp\SQLServer2019.exe

    - name: Install MSSQL Server
      win_shell: |
        Start-Process -FilePath C:\Temp\SQLServer2019.exe -ArgumentList '/qs', '/ACTION=Install', '/FEATURES=SQLENGINE', '/INSTANCENAME=MSSQLSERVER', '/SECURITYMODE=SQL', '/SAPWD=YourStrong!Passw0rd', '/IACCEPTSQLSERVERLICENSETERMS' -NoNewWindow -Wait
      args:
        executable: powershell.exe

    - name: Ensure MSSQL service is running
      win_service:
        name: MSSQLSERVER
        start_mode: auto
        state: started

    - name: Create SQL script to grant sysadmin permissions
      win_copy:
        content: |
          USE [master];
          GO
          ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\SYSTEM];
          GO
        dest: C:\Temp\grant_sysadmin.sql

    - name: Execute SQL script to grant sysadmin permissions
      win_shell: |
        sqlcmd -S .\MSSQLSERVER -i C:\Temp\grant_sysadmin.sql
      args:
        executable: cmd.exe

    - name: Clean up installation files and scripts
      win_file:
        path: C:\Temp\SQLServer2019.exe
        state: absent

    - name: Clean up SQL script
      win_file:
        path: C:\Temp\grant_sysadmin.sql
        state: absent
