---
- name: CONFIGURING FILESERVER
  hosts: FS
  gather_facts: no
  tasks:
    - name: Copy directory to shared folder
      win_copy:
        src: ../playbooks/Snare-Products
        dest: C:/Snare-Products
        recurse: yes
