---
- name: CONFIGURING DOMAIN CONTROLLER
  hosts: DC
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename
      
    - name: Reboot after rename
      win_reboot:
      when: rename.reboot_required
   
    - name: Installing Active Directory and DNS Server Role
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: result

    - name: Change Administrator password
      win_user:
        name: Administrator
        password: "{{ domain_admin_password }}"

    - name: Create domain
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ domain_short }}"
        safe_mode_password: "{{ safe_mode_pass }}"
        reboot: true

    - name: Set internal DNS server 
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
        - '127.0.0.1'

    - name: Configure DNS forwarders
      ansible.windows.win_powershell:
        script: |
          Set-DNSServerForwarder -IPAddress {{ dns_forwarders }}

    - name: Allow RDP to specific users
      ansible.windows.win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
        - Administrators

    - name: Disable Password Complexity
      win_shell: |
        Import-Module ActiveDirectory
        $domain = (Get-ADDomain).DistinguishedName
        $policy = Get-ADDefaultDomainPasswordPolicy -Identity $domain
        $policy.ComplexityEnabled = $false
        Set-ADDefaultDomainPasswordPolicy -Identity $domain -ComplexityEnabled $false
      args:
        executable: powershell.exe

    - name: Add snaretest account (ws2 account)
      microsoft.ad.user:
        name: '{{ first_user }}'
        firstname: snare
        surname: test
        password: '{{ first_user_password }}'
        state: present
        domain_username: Administrator
        domain_password: '{{ domain_admin_password }}'
        groups:
          set:
          - Domain Users
          - Remote Desktop Users
          - Administrators
          - Domain Admin

    - name: Re-enable Password Complexity
      win_shell: |
        Import-Module ActiveDirectory
        $domain = (Get-ADDomain).DistinguishedName
        $policy = Get-ADDefaultDomainPasswordPolicy -Identity $domain
        $policy.ComplexityEnabled = $true
        Set-ADDefaultDomainPasswordPolicy -Identity $domain -ComplexityEnabled $true
      args:
        executable: powershell.exe
