---
- name: CONFIGURING FILESERVER
  hosts: FS
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename
      
    - name: Reboot after rename
      win_reboot:
      when: rename.reboot_required
      
    - name: Set DNS to Domain Controller
      win_dns_client:
        adapter_names: '*'
        dns_servers:
        - "{{ hostvars['DC']['ansible_host'] }}"

    - name: Join Domain
      microsoft.ad.membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: Administrator@{{ domain_name }}
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: true
        
    - name: Set autologon for specific user
      community.windows.win_auto_logon:
        username: '{{ domain_admin_login }}'
        password: '{{ domain_admin_password }}'

    - name: Allow RDP to specific users
      ansible.windows.win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
        - Administrators

    - name: Installing FS-FileServer feature
      win_feature:
        name:
          - FS-FileServer
        include_sub_features: yes
        state: present

    - name: Creating SharedFolder directory
      win_file:
        path: C:\Snare-Products
        state: directory

    - name: Copy directory to shared folder
      win_copy:
        src: ../playbooks/Snare-Products
        dest: C:/Snare-Products
        recurse: yes

    - name: Creating FileServer shared folder
      win_share:
        name: Snare-Products
        description: All-in shared folder
        path: C:\Snare-Products
        list: yes
        full: '{{ domain_short }}\Domain Admins'
        change: '{{ domain_short }}\Domain Users'
        read: Everyone

    - name: Set autologon for specific user
      community.windows.win_auto_logon:
        username: '{{ domain_admin_login }}'
        password: '{{ domain_admin_password }}'

