---
- name: Copy Files to File Server
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy directory to shared folder
      win_copy:
        src: ../playbooks/SharedFolder
        dest: C:/Snare-Products
        recurse: yes
      register: copy_files

    - name: Debug copy files result
      debug:
        msg: "Copy directory to shared folder result: {{ copy_files }}"

    - name: Debug final reboot initiation
      debug:
        msg: "Rebooting the server to apply all configurations"

    - name: Force reboot the server after all tasks are done
      win_reboot:
      register: final_reboot_status

    - name: Wait for server to come back online after final reboot
      wait_for_connection:
        timeout: 600
      when: final_reboot_status.changed
