---
- name: Install and Configure Telegraf on Windows Hosts
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure 'C:\Temp' directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Download Telegraf Binary
      win_get_url:
        url: https://dl.influxdata.com/telegraf/releases/telegraf-1.31.0_windows_amd64.zip
        dest: C:\Temp\telegraf-1.31.0_windows_amd64.zip

    - name: Ensure 'C:\Program Files\InfluxData\telegraf' directory exists
      win_file:
        path: C:\Program Files\InfluxData\telegraf
        state: directory

    - name: Extract Telegraf archive
      win_unzip:
        src: C:\Temp\telegraf-1.31.0_windows_amd64.zip
        dest: C:\Program Files\InfluxData\telegraf
        creates: C:\Program Files\InfluxData\telegraf\telegraf.exe

    - name: Create Telegraf configuration file
      win_copy:
        content: |
          # Global Agent Configuration
          [agent]
            interval = "10s"
            round_interval = true
            metric_batch_size = 1000
            metric_buffer_limit = 10000
            collection_jitter = "0s"
            flush_interval = "10s"
            flush_jitter = "0s"
            precision = ""
            hostname = ""
            omit_hostname = false

          # Output Plugin - InfluxDB
          [[outputs.influxdb]]
            urls = ["http://192.168.10.94:8086"]
            database = "telegraf"
            username = "snare"
            password = "snare"
            skip_database_creation = true

          # CPU Input Plugin
          [[inputs.cpu]]
            percpu = true
            totalcpu = true
            collect_cpu_time = false
            report_active = true

          # Memory Input Plugin
          [[inputs.mem]]

          # Disk Input Plugin
          [[inputs.disk]]
            ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "squashfs", "nsfs"]

          # Network Interface Input Plugin
          [[inputs.net]]

          # System Input Plugin
          [[inputs.system]]

          # Windows Services Input Plugin
          [[inputs.win_services]]
            service_names = ["Snare", "snareAM", "sshd"]

        dest: C:\Program Files\InfluxData\telegraf\telegraf.conf
        force: yes

    - name: Install Telegraf service
      win_shell: |
        cd "C:\Program Files\InfluxData\telegraf"
        .\telegraf.exe --service install --config "C:\Program Files\InfluxData\telegraf\telegraf.conf"
      args:
        executable: powershell

    - name: Start Telegraf service
      win_service:
        name: telegraf
        state: started
        start_mode: auto
