- name: CONFIGURING WORKSTATION 1
  hosts: WS1
  gather_facts: no
  tasks:
  - name: Map shared folder
      community.windows.win_mapped_drive:
        letter: 'Z'
        path: \\fs.{{ domain_name }}\Snare-Products
        state: present
