- name: CONFIGURING WORKSTATION 1
  hosts: WS1
  gather_facts: no
  tasks:
    - name: Rename server
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename
      
    - name: Reboot after rename
      win_reboot:
      when: rename.reboot_required
      
    - name: Set DNS to Domain Controller
      win_dns_client:
        adapter_names: '*'
        dns_servers:
        - "{{ hostvars['DC']['ansible_host'] }}"
      
    - name: Join Domain
      microsoft.ad.membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: Administrator@{{ domain_name }}
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        reboot: true

    - name: Allow RDP to specific users
      ansible.windows.win_user_right:
        name: SeRemoteInteractiveLogonRight
        users:
        - Administrators
        - Remote Desktop Users

    - name: Map shared folder
      community.windows.win_mapped_drive:
        letter: 'Z'
        path: \\fs.{{ domain_name }}\Snare-Products
        state: present
        
    - name: Add user to rdp group
      win_group_membership:
        name: Remote Desktop Users
        members:
          - '{{ fs_admin_login }}'
        state: present

     - name: Set autologon for specific user
      community.windows.win_auto_logon:
        username: '{{ domain_admin_login }}'
        password: '{{ domain_admin_password }}'
